### ISSUE TITLE
Ensemble Viewer: compute statistics across ensemble members

### ISSUE THREAD

**Issue by sharkcooper** [HydrologicEngineeringCenter/FIRO_TSEnsembles#102]
Currently, Ensemble Viewer only shows data and statistics across time. However, we also want to display statistics on a separate graph that computes across ensemble members too.

**Comment by sharkcooper** [comment]
So far we've been using JFreeChart's built in TimeSeriesChart to render our graph, but now we need something like an XYPlot to create our graph across ensemble members. I'll do some research on this and see what I can find.

**Comment by sharkcooper** [comment]
Probably can use XYSeries for this, documentation for it is here: https://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/xy/XYSeries.html

**Comment by dvdhoz** [comment]
Feedback from Beth is to have this view be in its own Tab.  Separate tabs for different graph views (time vs ensemble on the x-axis)

**Comment by dvdhoz** [comment]
Branch has been committed and pushed based on our paired programming efforts.

**Comment by dvdhoz** [comment]
Things that still need to be cleaned up:
-statistics panel changes based on the chart type
-for Scatter plot, allowing different colors to show for each stat compute
-for Scatter plot, tool tips needs to be updated

**Comment by dvdhoz** [comment]
Scatter plot now has different colors per stat and tool tips show ensemble number as the x value instead of date)

Noticed a few bugs:
1. if selecting multiple stats in the Across Ensembles view, the point shapes change as you add more stats (i.e. the max value shape changes from circle to a square).  Want to keep the shape the same as you add stats.
2. when toggling between time plot and the scatterplot, checked stats are not always shown.  Have to re-check the checkmark for it to show.  Need a way to refresh?
